# Generated by Django 5.0.3 on 2024-03-16 11:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='store/pdfs/')),
                ('regNo', models.CharField(default='I19', max_length=100, validators=[django.core.validators.RegexValidator(code='invalid Registration Number', message='Only Alphanumeric is allowed.', regex='[0-9a-zA-Z]')])),
                ('Name', models.CharField(default='UnknownPrint', max_length=100)),
                ('category', models.CharField(default='Student', max_length=10)),
            ],
        ),
    ]
