# Generated by Django 4.2.7 on 2024-04-04 05:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='store/store/pdfs/')),
                ('regNo', models.CharField(default='I19', max_length=100, validators=[django.core.validators.RegexValidator(code='invalid Registration Number', message='Only Alphanumeric is allowed.', regex='[0-9a-zA-Z]')])),
                ('Name', models.CharField(default='UnknownPrint', max_length=100)),
                ('category', models.CharField(default='Student', max_length=10)),
                ('PaperSize', models.CharField(default='A4', max_length=150)),
                ('color', models.CharField(default='Black and White', max_length=155)),
                ('PagesPerSheet', models.IntegerField(default=1)),
                ('printSide', models.CharField(default='Single', max_length=155)),
                ('Pages', models.CharField(default='All', max_length=150)),
                ('numberOfCopies', models.IntegerField(default=1)),
                ('Layout', models.CharField(default='Potrait', max_length=150)),
                ('whatsapp', models.CharField(default='9426034129', max_length=255)),
            ],
        ),
    ]
