# Generated by Django 5.0.3 on 2024-03-18 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='Layout',
            field=models.CharField(default='Potrait', max_length=150),
        ),
        migrations.AddField(
            model_name='files',
            name='Pages',
            field=models.CharField(default='All', max_length=150),
        ),
        migrations.AddField(
            model_name='files',
            name='PagesPerSheet',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='files',
            name='PaperSize',
            field=models.CharField(default='A4', max_length=150),
        ),
        migrations.AddField(
            model_name='files',
            name='color',
            field=models.CharField(default='Black and White', max_length=155),
        ),
        migrations.AddField(
            model_name='files',
            name='numberOfCopies',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='files',
            name='printSide',
            field=models.CharField(default='Single', max_length=155),
        ),
    ]
