# Generated by Django 4.2.7 on 2024-04-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0003_alter_files_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='status',
            field=models.CharField(default='UPLOADED', max_length=255),
        ),
    ]
