# Generated by Django 4.2.7 on 2024-04-17 17:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0005_remove_files_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
