# Generated by Django 4.2.7 on 2024-04-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0006_files_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='last_updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
