# Generated by Django 4.2.7 on 2024-04-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0007_files_last_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
