# Generated by Django 4.2.7 on 2024-04-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0008_alter_files_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='verifycode',
            field=models.IntegerField(default=283721),
            preserve_default=False,
        ),
    ]
