# Generated by Django 4.2.7 on 2024-04-18 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0009_files_verifycode'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='price',
            field=models.FloatField(default=10.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='files',
            name='token',
            field=models.CharField(default=12, max_length=10),
            preserve_default=False,
        ),
    ]
